"""initial schema baseline

Revision ID: 442b783e2edf
Revises: 
Create Date: 2026-04-24 12:11:00.899039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442b783e2edf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_index(op.f('ix_brand_keywords_id'), 'brand_keywords', ['id'], unique=False)
    op.create_table('domain_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('risk_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_domain_blacklist_id'), 'domain_blacklist', ['id'], unique=False)
    op.create_table('domain_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('list_type', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_list_items_host'), 'domain_list_items', ['host'], unique=False)
    op.create_index(op.f('ix_domain_list_items_id'), 'domain_list_items', ['id'], unique=False)
    op.create_index(op.f('ix_domain_list_items_list_type'), 'domain_list_items', ['list_type'], unique=False)
    op.create_index(op.f('ix_domain_list_items_owner_id'), 'domain_list_items', ['owner_id'], unique=False)
    op.create_index(op.f('ix_domain_list_items_owner_type'), 'domain_list_items', ['owner_type'], unique=False)
    op.create_index(op.f('ix_domain_list_items_source'), 'domain_list_items', ['source'], unique=False)
    op.create_index(op.f('ix_domain_list_items_status'), 'domain_list_items', ['status'], unique=False)
    op.create_table('domain_whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_domain_whitelist_id'), 'domain_whitelist', ['id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index(op.f('ix_model_versions_id'), 'model_versions', ['id'], unique=False)
    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_settings_id'), 'platform_settings', ['id'], unique=False)
    op.create_index(op.f('ix_platform_settings_key'), 'platform_settings', ['key'], unique=True)
    op.create_table('report_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_actions_action_type'), 'report_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_report_actions_actor'), 'report_actions', ['actor'], unique=False)
    op.create_index(op.f('ix_report_actions_id'), 'report_actions', ['id'], unique=False)
    op.create_index(op.f('ix_report_actions_report_id'), 'report_actions', ['report_id'], unique=False)
    op.create_table('risk_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_index(op.f('ix_risk_keywords_id'), 'risk_keywords', ['id'], unique=False)
    op.create_table('rule_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_key', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('pattern', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_key')
    )
    op.create_index(op.f('ix_rule_configs_id'), 'rule_configs', ['id'], unique=False)
    op.create_table('user_site_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('strategy_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_site_strategies_domain'), 'user_site_strategies', ['domain'], unique=False)
    op.create_index(op.f('ix_user_site_strategies_id'), 'user_site_strategies', ['id'], unique=False)
    op.create_index(op.f('ix_user_site_strategies_username'), 'user_site_strategies', ['username'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('scan_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('rule_score', sa.Float(), nullable=False),
    sa.Column('model_safe_prob', sa.Float(), nullable=False),
    sa.Column('model_suspicious_prob', sa.Float(), nullable=False),
    sa.Column('model_malicious_prob', sa.Float(), nullable=False),
    sa.Column('has_password_input', sa.Boolean(), nullable=True),
    sa.Column('hit_rules_json', sa.JSON(), nullable=True),
    sa.Column('raw_features_json', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_records_id'), 'scan_records', ['id'], unique=False)
    op.create_index(op.f('ix_scan_records_report_id'), 'scan_records', ['report_id'], unique=False)
    op.create_index(op.f('ix_scan_records_user_id'), 'scan_records', ['user_id'], unique=False)
    op.create_table('training_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_runs_id'), 'training_runs', ['id'], unique=False)
    op.create_table('user_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('auto_detect', sa.Boolean(), nullable=True),
    sa.Column('auto_block_malicious', sa.Boolean(), nullable=True),
    sa.Column('notify_suspicious', sa.Boolean(), nullable=True),
    sa.Column('bypass_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('plugin_enabled', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_policies_id'), 'user_policies', ['id'], unique=False)
    op.create_index(op.f('ix_user_policies_user_id'), 'user_policies', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_policies_username'), 'user_policies', ['username'], unique=True)
    op.create_table('plugin_sync_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_label', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('scan_record_id', sa.Integer(), nullable=True),
    sa.Column('plugin_version', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scan_record_id'], ['scan_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_sync_events_action'), 'plugin_sync_events', ['action'], unique=False)
    op.create_index(op.f('ix_plugin_sync_events_domain'), 'plugin_sync_events', ['domain'], unique=False)
    op.create_index(op.f('ix_plugin_sync_events_event_type'), 'plugin_sync_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_plugin_sync_events_host'), 'plugin_sync_events', ['host'], unique=False)
    op.create_index(op.f('ix_plugin_sync_events_id'), 'plugin_sync_events', ['id'], unique=False)
    op.create_index(op.f('ix_plugin_sync_events_risk_label'), 'plugin_sync_events', ['risk_label'], unique=False)
    op.create_index(op.f('ix_plugin_sync_events_risk_level'), 'plugin_sync_events', ['risk_level'], unique=False)
    op.create_index(op.f('ix_plugin_sync_events_scan_record_id'), 'plugin_sync_events', ['scan_record_id'], unique=False)
    op.create_index(op.f('ix_plugin_sync_events_user_id'), 'plugin_sync_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_plugin_sync_events_username'), 'plugin_sync_events', ['username'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('matched_rules', sa.JSON(), nullable=True),
    sa.Column('page_signals', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scan_record_id'], ['scan_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_host'), 'reports', ['host'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_risk_level'), 'reports', ['risk_level'], unique=False)
    op.create_index(op.f('ix_reports_scan_record_id'), 'reports', ['scan_record_id'], unique=True)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('feedback_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('related_report_id', sa.Integer(), nullable=True),
    sa.Column('related_event_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['related_event_id'], ['plugin_sync_events.id'], ),
    sa.ForeignKeyConstraint(['related_report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['scan_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_cases_domain'), 'feedback_cases', ['domain'], unique=False)
    op.create_index(op.f('ix_feedback_cases_feedback_type'), 'feedback_cases', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_feedback_cases_id'), 'feedback_cases', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_cases_related_event_id'), 'feedback_cases', ['related_event_id'], unique=False)
    op.create_index(op.f('ix_feedback_cases_related_report_id'), 'feedback_cases', ['related_report_id'], unique=False)
    op.create_index(op.f('ix_feedback_cases_report_id'), 'feedback_cases', ['report_id'], unique=False)
    op.create_index(op.f('ix_feedback_cases_source'), 'feedback_cases', ['source'], unique=False)
    op.create_index(op.f('ix_feedback_cases_status'), 'feedback_cases', ['status'], unique=False)
    op.create_index(op.f('ix_feedback_cases_user_id'), 'feedback_cases', ['user_id'], unique=False)
    op.create_index(op.f('ix_feedback_cases_username'), 'feedback_cases', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_cases_username'), table_name='feedback_cases')
    op.drop_index(op.f('ix_feedback_cases_user_id'), table_name='feedback_cases')
    op.drop_index(op.f('ix_feedback_cases_status'), table_name='feedback_cases')
    op.drop_index(op.f('ix_feedback_cases_source'), table_name='feedback_cases')
    op.drop_index(op.f('ix_feedback_cases_report_id'), table_name='feedback_cases')
    op.drop_index(op.f('ix_feedback_cases_related_report_id'), table_name='feedback_cases')
    op.drop_index(op.f('ix_feedback_cases_related_event_id'), table_name='feedback_cases')
    op.drop_index(op.f('ix_feedback_cases_id'), table_name='feedback_cases')
    op.drop_index(op.f('ix_feedback_cases_feedback_type'), table_name='feedback_cases')
    op.drop_index(op.f('ix_feedback_cases_domain'), table_name='feedback_cases')
    op.drop_table('feedback_cases')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_scan_record_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_risk_level'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_host'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_plugin_sync_events_username'), table_name='plugin_sync_events')
    op.drop_index(op.f('ix_plugin_sync_events_user_id'), table_name='plugin_sync_events')
    op.drop_index(op.f('ix_plugin_sync_events_scan_record_id'), table_name='plugin_sync_events')
    op.drop_index(op.f('ix_plugin_sync_events_risk_level'), table_name='plugin_sync_events')
    op.drop_index(op.f('ix_plugin_sync_events_risk_label'), table_name='plugin_sync_events')
    op.drop_index(op.f('ix_plugin_sync_events_id'), table_name='plugin_sync_events')
    op.drop_index(op.f('ix_plugin_sync_events_host'), table_name='plugin_sync_events')
    op.drop_index(op.f('ix_plugin_sync_events_event_type'), table_name='plugin_sync_events')
    op.drop_index(op.f('ix_plugin_sync_events_domain'), table_name='plugin_sync_events')
    op.drop_index(op.f('ix_plugin_sync_events_action'), table_name='plugin_sync_events')
    op.drop_table('plugin_sync_events')
    op.drop_index(op.f('ix_user_policies_username'), table_name='user_policies')
    op.drop_index(op.f('ix_user_policies_user_id'), table_name='user_policies')
    op.drop_index(op.f('ix_user_policies_id'), table_name='user_policies')
    op.drop_table('user_policies')
    op.drop_index(op.f('ix_training_runs_id'), table_name='training_runs')
    op.drop_table('training_runs')
    op.drop_index(op.f('ix_scan_records_user_id'), table_name='scan_records')
    op.drop_index(op.f('ix_scan_records_report_id'), table_name='scan_records')
    op.drop_index(op.f('ix_scan_records_id'), table_name='scan_records')
    op.drop_table('scan_records')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_site_strategies_username'), table_name='user_site_strategies')
    op.drop_index(op.f('ix_user_site_strategies_id'), table_name='user_site_strategies')
    op.drop_index(op.f('ix_user_site_strategies_domain'), table_name='user_site_strategies')
    op.drop_table('user_site_strategies')
    op.drop_index(op.f('ix_rule_configs_id'), table_name='rule_configs')
    op.drop_table('rule_configs')
    op.drop_index(op.f('ix_risk_keywords_id'), table_name='risk_keywords')
    op.drop_table('risk_keywords')
    op.drop_index(op.f('ix_report_actions_report_id'), table_name='report_actions')
    op.drop_index(op.f('ix_report_actions_id'), table_name='report_actions')
    op.drop_index(op.f('ix_report_actions_actor'), table_name='report_actions')
    op.drop_index(op.f('ix_report_actions_action_type'), table_name='report_actions')
    op.drop_table('report_actions')
    op.drop_index(op.f('ix_platform_settings_key'), table_name='platform_settings')
    op.drop_index(op.f('ix_platform_settings_id'), table_name='platform_settings')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_model_versions_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_domain_whitelist_id'), table_name='domain_whitelist')
    op.drop_table('domain_whitelist')
    op.drop_index(op.f('ix_domain_list_items_status'), table_name='domain_list_items')
    op.drop_index(op.f('ix_domain_list_items_source'), table_name='domain_list_items')
    op.drop_index(op.f('ix_domain_list_items_owner_type'), table_name='domain_list_items')
    op.drop_index(op.f('ix_domain_list_items_owner_id'), table_name='domain_list_items')
    op.drop_index(op.f('ix_domain_list_items_list_type'), table_name='domain_list_items')
    op.drop_index(op.f('ix_domain_list_items_id'), table_name='domain_list_items')
    op.drop_index(op.f('ix_domain_list_items_host'), table_name='domain_list_items')
    op.drop_table('domain_list_items')
    op.drop_index(op.f('ix_domain_blacklist_id'), table_name='domain_blacklist')
    op.drop_table('domain_blacklist')
    op.drop_index(op.f('ix_brand_keywords_id'), table_name='brand_keywords')
    op.drop_table('brand_keywords')
    # ### end Alembic commands ###
